labels:
  - name: 0 - Backlog
    labeled:
      issue:
        body: This Feature Request was accepted, but are not going to be implemented in next release.
        action: open    
  - name: need specification
    labeled:
      issue:
        body: This Feature Request was accepted and is ready for specfication.
        action: open
  - name: 2 - Ready
    labeled:
      issue:
        body: This Feature is ready to be implemented.
        action: open            
  - name: need tester
    labeled:
      issue:
        body: |
          This feature have been implemented and is ready for Funcional Test.
          Please, test the feature.
  - name: 'failed :red_circle:'
    labeled:
      issue:
        body: | 
          Functional Test failed!
          Please, review your solution.
          *****
          Please, move to CODED only when this feature is **fully implemented**: bugs reported in comments and requirements in OP
          If you want to request a test of some partial solution, add a comment here with test tean @
        action: open
  - name: 'passed :large_blue_circle:'
    labeled:
      issue:
        body: | 
          Functional Test passed!
          Please, make a PULL REQUEST or, if already merged, close the issue.
        action: open        
    #pr:
    #body: Please follow the pull request templates.
    #action: close
    #unlabeled:
    #issue:
    #body: Thank you for following the template. The repository owner will reply.
    #action: open
  - name: 'resolution:WontFix'
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: 'resolution:Not Reproducible'
    labeled:
      issue:
        body: We couldn't reprocuce the bug.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: 'resolution:Duplicate'
    labeled:
      issue:
        body: This issue request already exists.
        action: close
      pr:
        body: This pull request already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
        action: open
