labels:
  - name: test-FTfailed
    labeled:
      issue:
        body: | 
          Functional Test failed!
          Please review your solution.
        action: open
  - name: test-FTsuccess
    labeled:
      issue:
        body: | 
          Functional Test passed!
          @owner Please open a PULL REQUEST.
        action: open        
      #pr:
        #body: Please follow the pull request templates.
        #action: close
    #unlabeled:
      #issue:
        #body: Thank you for following the template. The repository owner will reply.
        #action: open
  - name: resolution-Won't fix
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open
  - name: resolution-duplicate
    labeled:
      issue:
        body: This issue or pull request already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
